sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t nlrcmani/docker-multicontainer-react -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true nlrcmani/docker-multicontainer-react npm test -- --coverage

after_success:
  - docker build -t nlrcmani/multi-client ./client
  - docker build -t nlrcmani/multi-nginx ./nginx
  - docker build -t nlrcmani/multi-server ./server
  - docker build -t nlrcmani/multi-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images 
  - docker push nlrcmani/multi-client
  - docker push nlrcmani/multi-nginx
  - docker push nlrcmani/multi-server
  - docker push nlrcmani/multi-worker


deploy:
  provider: elasticbeanstalk
  region: $AWS_REGION
  app: $AWS_EBS_APP_NAME
  env: $AWS_EBS_ENV_NAME
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: $AWS_BUCKET_PATH
  on:
   branch: $AWS_BRANCH
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

